# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j-zAuuZKOFmC6Tui5RczfoTKPHj9vEiV
"""
import keras.models
import tensorflow as tf
import tensorflow_hub as hub
import os

def build_model_local():
    """
    For sandbox
    :return: nnlm model
    """
    #this is for getting data in parent directory
    parentDirectory = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
    hub_layer =tf.keras.models.load_model(os.path.join(parentDirectory, 'resources', 'Model', 'nnlm_128_dim'))
    return hub_layer


def build_model():
    "Return Hub nnlm-id-dim128 model"
    hub_layer = hub.KerasLayer("https://tfhub.dev/google/nnlm-id-dim128/2", output_shape=[50],
                               input_shape=[], dtype=tf.string)
    return hub_layer


